### ISSUE TITLE
Add history statement to smartregister.org

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp.github.io#1]
@rowo 

The OpenSRP platform was initially developed for the Dristhi project, a Wellcome Trust research project, which is currently underway in Karnataka, India with nurse-midwives in rural healthcare settings.  The Foundation for Research in Health Systems (FRHS), WHO Department of Reproductive Health and Research, and the Sustainable Engineering Lab (SEL) at Columbia are founding partners of the Dristhi project, with ThoughtWorks providing initial engineering as a key technology partner.  In addition to the generous support of the Wellcome Trust, financial support for the OpenSRP platform has been provided by the Norwegian Agency for Development Cooperation, The Bill and Melinda Gates Foundation, WHO, and the UNDP—UNFPA—UNICEF—WHO—World Bank Special Programme of Research, Development and Research Training in Human Reproduction (HRP).

**Comment by rowo** [comment]
@cagulas Will info about the different sites added to this eventually? So I should put it into it's own page?

**Comment by cafootitt** [comment]
@rowo 

Hm, so the content on the 3 country sites will be its own page, but this is related to the history, so I think the intent was to add it to the main page -- it's more so to give credit to the original partners somewhere on the site...eventually there can be additional pages about the history and the India deployment.  For now, I think let's put it on the main page - somewhere around the founding partner logos
