### ISSUE TITLE
Add technology vendors to Technologies & Vendors page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp.github.io#13]
Will wait to receive text that is due next week from each tech vendor.

**Comment by cafootitt** [comment]
No longer blocked.  Content is [here](https://docs.google.com/document/d/1nx7KSOGy1GyLFidpyJa7vwC38eBcYYfn5Z353FTsp2U/edit).

**Comment by rowo** [comment]
"Add to the existing page, below existing content in a **Vendors** section."
