### ISSUE TITLE
Investigate option of changing wiki domain name

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp.github.io#2]
Change from https://smartregister.atlassian.net/wiki to wiki.smartregister.org or wiki.opensrp.org.

https://confluence.atlassian.com/display/CLOUDKB/Changing+the+Cloud+instance+URL+address

**Comment by ndisha** [comment]
Hey @cagulas did the Atlassian team get back to you on this from the mail we wrote to them while in Dhaka?
