### ISSUE TITLE
Updates to partners on OpenSRP home page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp.github.io#32]
Make the following changes to the OpenSRP home page (http://smartregister.org/)

With generous support from section:
- [x] Remove Grameen
- [x] Remove Pepfar
- [x] Remove Gates Foundation
- [x] Add WHO
- [x] Replace UNICEF with UNICEF Innovations
- [x] Add Qualcomm Wireless Reach

Add a new section underneath support section, **With Technology Partners**:
- [x] Ona
- [x] IHS
- [x] Summit
- [x] mPower
- [x] OpenMRS
- [x] SEL
- [x] RapidPro

Change the **Implementing Partners** section to **With Health, Research, and Implementation Partners** and list the following organizations:
- [x] WHO
- [x] JHU-GMI
- [x] Summit Institute
- [x] IRD
- [x] Harvard School of Public Health
- [x] FRHS
- [x] Earth Institute
- [x] UNICEF

(Remove Jhpiego, OpenHIE, Jembi, and TW from this section)

**Comment by rowo** [comment]
@cagulas Wasn't thinking and didn't do my work in a new branch. However, it's up now. Can you take a look at http://smartregister.org/ and close if okay?

**Comment by cafootitt** [comment]
Add back UBS to first section
