### ISSUE TITLE
Separate OpenSRP features into new page 

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp.github.io#9]
Put the OpenSRP features section from this [page](http://smartregister.org/tech-different.html), as a separate page under the technology header.

**Comment by rowo** [comment]
@cagulas I thought the Smart Registers and Features were both part of "How it's different". Otherwise, "How is it different" is just about smart registers.. is that right?

**Comment by cafootitt** [comment]
Yes, that's right.  Just double-checked with Tigest again, and features should be moved to its own page.
